"""email-unique-false

Revision ID: 1275597e6004
Revises: 20e1a9adf6b5
Create Date: 2023-04-08 16:32:37.580146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1275597e6004'
down_revision = '20e1a9adf6b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('contact_email_key', 'contact', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('contact_email_key', 'contact', ['email'])
    # ### end Alembic commands ###
