"""birthday--Date

Revision ID: 20e1a9adf6b5
Revises: b10ffacef151
Create Date: 2023-04-08 16:31:15.592786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20e1a9adf6b5'
down_revision = 'b10ffacef151'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
